# Generated by Django 5.1.5 on 2025-01-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codearc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='skils',
            new_name='skills',
        ),
    ]
