# Generated by Django 5.1.5 on 2025-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codearc', '0002_rename_skils_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.CharField(default=True, max_length=5000),
        ),
    ]
