# Generated by Django 5.1.5 on 2025-02-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codearc', '0003_course_featured_img_course_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='catogary',
            new_name='categary',
        ),
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
