# Generated by Django 5.1.5 on 2025-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codearc', '0004_rename_catogary_course_categary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
